Script started on Fri Nov  6 11:20:52 2015
bash-3.2$ ./../bin/rshell
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ ls -l; pwd; echo hello world;
total 16
-rw-r--r--  1 justinmoy  staff	 43 Nov  6 11:20 multi_command.script
-rwxrwx--x@ 1 justinmoy  staff	853 Nov  6 11:18 multi_command.sh
/Users/justinmoy/Documents/CS100/Assignment1/rshell/tests
hello world
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ ls -l ; pwd; echo spaces test
total 16
-rw-r--r--  1 justinmoy  staff	 43 Nov  6 11:20 multi_command.script
-rwxrwx--x@ 1 justinmoy  staff	853 Nov  6 11:18 multi_command.sh
/Users/justinmoy/Documents/CS100/Assignment1/rshell/tests
spaces test
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ echo testing and connector && echo works!
testing and connector
works!
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ echo testing and with semi && echo ayay!; pwd && ls;
testing and with semi
ayay!
/Users/justinmoy/Documents/CS100/Assignment1/rshell/tests
multi_command.script	multi_command.sh
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ echo testing failed or || echo ddont run
testing failed or
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ this wont run || echo the or works! && pwd; ls -a
execvp() errrr: No such file or directory
the or works!
/Users/justinmoy/Documents/CS100/Assignment1/rshell/tests
.			.DS_Store		multi_command.script
..			.multi_command.sh.swp	multi_command.sh
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ this wont run || echo this works! && mkdir testdir; ls -l && rmdir testdir
execvp() errrr: No such file or directory
this works!
total 16
-rw-r--r--  1 justinmoy  staff	1206 Nov  6 11:22 multi_command.script
-rwxrwx--x@ 1 justinmoy  staff	 853 Nov  6 11:18 multi_command.sh
drwxr-xr-x  2 justinmoy  staff	  68 Nov  6 11:22 testdir
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ echo testing connectors with spaces &&    pwd    && echo it works!
testing connectors with spaces
/Users/justinmoy/Documents/CS100/Assignment1/rshell/tests
it works!
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ echo testing && echo and && echo chaining  & echo with spaces; echo and semicolons
testing
and
chaining & echo with spaces
and semicolons
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ ls l || echo this works!! && mkdir testdir; ls -l && rmdir testdir; pwd
ls: l: No such file or directory
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ ls a || echo failed ls command should run this
ls: a: No such file or directory
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ echo chaining semicolon; echo with a failed cmd; this will fail; echo this should output!
chaining semicolon
with a failed cmd
execvp() errrr: No such file or directory
this should output!
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ ls a && echo this wont echo || echo this should echo ; pwd
ls: a: No such file or directory
this wont echo
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ exit
this should output!
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ exit
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ exit
[justinmoy@ ucrwpa3-3-217-25.bulk.ucr.edu]$ exit
bash-3.2$ exit
exit

Script done on Fri Nov	6 11:24:30 2015
